canonical/temporal-k8s-operator

- README.md
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/loki_k8s/v0/loki_push_api.py
- lib/charms/observability_libs/v0/juju_topology.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- metadata.yaml
- src/charm.py
- src/grafana_dashboards/README.md
- src/grafana_dashboards/temporal-monitoring.json.tmpl
- src/prometheus_alert_rules/README.md
- src/relations.py
- src/state.py
- templates/config.jinja
- tests/unit/test_charm.py
- tox.ini
This PR addresses two aspects:
1. It switches from the use of `StoredState` to store and share configuration to the use of peer relations as it is [better recommended](https://juju.is/docs/sdk/stored-state-uses-limitations). This is reflected in:
- `state.py`: Definition of the State class.
- `charm.py`: Use of the peer relation state and refactoring nested state updates (`_update_db_connections` helper method was needed to achieve this).
- `relations.py`: Light refactoring to reflect the new state being used.
2. It integrates the charm with the [Canonical Observability Stack](https://charmhub.io/topics/canonical-observability-stack/editions/lite). This is reflected in:
- `charm.py`: Include relations for Grafana, Prometheus and Loki.
- `grafana_dashboards/temporal-monitoring.json.tmpl`: …
> CSS-3245: Integrate with cos-lite and switch to peer relation

- .licenserc.yaml
- CONTRIBUTING.md
- README.md
- actions.yaml
- charmcraft.yaml
- config.yaml
- lib/charms/data_platform_libs/v0/database_requires.py
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/nginx_ingress_integrator/v0/nginx_route.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- metadata.yaml
- pyproject.toml
- src/charm.py
- src/log.py
- src/relations.py
- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/temporal_client/activities.py
- tests/integration/temporal_client/run_worker.py
- tests/integration/temporal_client/trigger_workflow.py
- tests/integration/temporal_client/workflows.py
- tests/integration/test_charm.py
- tests/unit/__init__.py
- tests/unit/test_charm.py
- tox.ini
- With the new [postgresql-k8s charm stable](https://discourse.canonical.com/t/juju-operators-for-postgresql-and-mysql-are-now-stable/1786) release, it is recommended that charms using the legacy “pgsql” interface should migrate to the modern “postgresql_client” interface. This PR addresses this by updating the pgsql interface to postgresql_client and modifying all related observers and tests.
- Added the "backend_protocol" annotation to the nginx ingress resource to specify the GRPC backend protocol.
> CSS-3775: update pgsql interface to modern postgresql_client interface

- .github/workflows/integration_test.yaml
- .github/workflows/test_and_publish_charm.yaml
- src/charm.py
- src/literals.py
- src/relations/__init__.py
- src/relations/admin.py
- src/relations/postgresql.py
- src/relations/ui.py
- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/test_charm.py
- tests/integration/test_scaling.py
- tests/unit/test_charm.py
- tox.ini
This PR aims to:
- Refactor the relations (admin, ui, postgresql) into separate files to make it easier to introduce new relations in the future.
- Fix the "publish to edge" workflow. With the introduction of the scaled deployment integration tests, there should be two separate integration tests run on two different models. However, the workflow runs them both on one model which causes issues. The change introduced runs the integration tests first, before running the "publish to edge" workflow and asking it to only run one of the integration test (test_charm).
> Refactor relations and fix "publish to edge" workflow

- .github/workflows/integration_test.yaml
- tests/integration/helpers.py
- tests/integration/test_upgrades.py
- tox.ini
This PR adds another integration test to check for the ability to safely upgrade to the newly released charm. The integration test deploys the charm from the latest channel available on Charmhub and upgrades it to the charm built from source. This ensures that the changes made in each PR are safe to upgrade to from the previous release.
> CSS-3455: Add safe upgrades integration test

- CONTRIBUTING.md
- config.yaml
- documentation/how-to/authorization.md
- documentation/how-to/scaling.md
- lib/charms/openfga_k8s/v0/openfga.py
- metadata.yaml
- requirements.txt
- src/charm.py
- src/literals.py
- src/relations/openfga.py
- src/relations/ui.py
- templates/config.jinja
- tests/integration/test_auth.py
- tests/integration/test_scaling.py
- tests/unit/test_charm.py
- tox.ini
This PR replaces the upstream image that has been used for the Temporal server charm thus far with the [custom image](https://github.com/canonical/charmed-temporal-image/pkgs/container/temporal-server) that was developed, which includes a custom authorizer using OpenFGA. The PR introduces the following:
- The addition of the `internal-frontend` service which is used by the server's `worker` service to bypass authorization rules.
- Modification of scaling instructions to include the `internal-frontend` service and how to include ingress and authorization with a scaled deployment.
- Modification of the `config.jinja` file to reflect the `internal-frontend` service as well as using the same database for [`visibility`](https://docs.temporal.io/visibility) and [`advanced …
> CSS-3634: Modify charm with custom image

- actions.yaml
- charmcraft.yaml
- config.yaml
- metadata.yaml
- pyproject.toml
- src/charm.py
- src/literals.py
- src/log.py
- src/relations/__init__.py
- src/relations/admin.py
- src/relations/openfga.py
- src/relations/postgresql.py
- src/relations/ui.py
- src/state.py
- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/temporal_client/activities.py
- tests/integration/temporal_client/workflows.py
- tests/integration/test_auth.py
- tests/integration/test_charm.py
- tests/integration/test_scaling.py
- tests/integration/test_upgrades.py
- tests/unit/__init__.py
- tests/unit/test_charm.py
- tox.ini
Due to the most recent "[Publish to edge](https://github.com/canonical/temporal-k8s-operator/actions/runs/7127968459)" action run failing, this PR attempts to see if updating some dependencies would solve this.
> Update license headers and dependencies

- src/charm.py
- templates/config.jinja
- tox.ini
To enable [advanced visibility](https://docs.temporal.io/visibility#advanced-visibility) using PostgreSQL, this PR changes the db type from `postgres` to `postgres12`. It also adds injects proxy config from the model into the workload container.
> Change visibility DB type and add proxy config

- src/charm.py
As the admin charm connects to the server on the frontend port `7233` to run `tctl` actions, enabling auth prevents the admin from connecting anymore due to the lack of authentication mechanisms in the admin charm. Given that the admin charm is deployed alongside the server, it does not have to be subject to auth rules and should be able to connect to the server directly. This can be achieved by exposing the service port `7236` of the `internal-frontend` service, which does not apply any auth rules, and having the admin charm connect to port `7236`.
> Open internal frontend service port

- documentation/tutorial/07-deploy-ingress.md
- src/charm.py
- tests/integration/helpers.py
- tests/integration/test_auth.py
- tests/integration/test_scaling.py
- tests/unit/test_charm.py
This PR does the following: 
- Adds a status check for the workload container which runs a tctl command to check cluster health before setting the charm's status to active.
- Adds a handler to reapply the pebble plan after a restart with the `pebble-ready` event to address this [bug](https://warthogs.atlassian.net/browse/CSS-6875) (See this [PR](https://github.com/canonical/superset-k8s-operator/pull/28) for reference).
- Slightly updates the tutorial instructions for enabling ingress.
> Add pebble plan validation

- documentation/how-to/authentication.md
- documentation/how-to/authorization.md
- documentation/how-to/tctl.md
- documentation/how-to/upgrade-server.md
- documentation/index.md
- documentation/tutorial/01-introduction.md
- documentation/tutorial/02-environment.md
- documentation/tutorial/03-deploy-server.md
- documentation/tutorial/04-deploy-db.md
- documentation/tutorial/05-deploy-admin.md
- documentation/tutorial/06-deploy-ui.md
- documentation/tutorial/07-deploy-ingress.md
- documentation/tutorial/08-deploy-worker.md
- documentation/tutorial/09-run-workflow.md
- documentation/tutorial/10-cleanup.md
This PR addresses the following:
- Adds a "How to" documentation page on how to perform server upgrades.
- Updates tctl documentation.
- Updates authorization documentation based on changes introduced in #29.
- Fixes documentation links so that they are accessible in Github.
> Add upgrade server and documentation updates

- config.yaml
- src/charm.py
- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/test_scaling.py
- tests/integration/test_upgrades.py
- tests/unit/test_charm.py
- tox.ini
This PR makes the number of [history shards](https://docs.temporal.io/clusters#history-shard) a configurable value at deployment time. This is a value that can only be set once at deployment time, so the mechanism to enforce this has been implemented at the charm level.
Note: Prior to this change, the number of history shards was set to 4 by default. Existing charmed Temporal deployments upgrading to this revision of the charm will be required to set the `num-history-shards` config to 4 for the charm to continue functioning.
> Make number of history shards configurable

- .github/workflows/integration_test.yaml
- documentation/how-to/upgrade-server.md
- templates/config.jinja
- tests/integration/test_server_upgrade.py
- tests/integration/test_upgrades.py
- tox.ini
This PR adds an integration test to test a server upgrade process which requires a schema update. This usually happens on the odd numbered minor versions of the Temporal server (i.e. `v1.19.0`, `v1.21.0`). 
This will be made possible through the charms by simply updating the admin charm revision followed by an update to the server charm revision as outlined in the docs.
> CSS-7092: Add server upgrade test

- documentation/how-to/upgrade-server.md
- lib/charms/data_platform_libs/v0/s3.py
- lib/charms/loki_k8s/v0/loki_push_api.py
- lib/charms/nginx_ingress_integrator/v0/nginx_route.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- src/charm.py
- src/literals.py
- src/relations/postgresql.py
- tests/integration/conftest.py
- tests/integration/test_auth.py
This PR is for triggering a Temporal server charm re-release to Charmhub with the latest image uploaded [here](https://github.com/canonical/charmed-temporal-image/pkgs/container/temporal-server), which upgrades the Temporal server image to `v1.23.1`. More info on this change can be found [here](https://github.com/canonical/charmed-temporal-image/pull/9).
> Upgrade server to v1.23.1

- CONTRIBUTING.md
- config.yaml
- documentation/how-to/scaling.md
- documentation/how-to/upgrade-server.md
- src/charm.py
- templates/dynamic_config.jinja
- tests/integration/conftest.py
- tests/integration/test_scaling.py
- tests/unit/test_charm.py
- tests/unit/test_state.py
This PR adds the following:
- Configurations for enabling rate limits by namespace as outlined [here](https://community.temporal.io/t/rate-limiting-by-namespace/1335). This should be done on a per-namespace basis, but I've also opened an issue to enable wildcard rule definitions [here](https://github.com/temporalio/temporal/issues/6237).
- Remove the need for an admin relation is the service is not `frontend`, as the admin charm only needs to be related to once for schema setup.
- Updates the relevant docs for the changes introduced in [this PR](https://github.com/canonical/temporal-admin-k8s-operator/pull/15).
Note: the libraries will not be updated in this PR as the update of the Loki library seems to deprecate the interface we are using, so a separate PR for this is in order.
> CSS-9372: Add namespace rate limits

- charmcraft.yaml
- documentation/how-to/observability.md
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/loki_k8s/v1/loki_push_api.py
- metadata.yaml
- requirements.txt
- src/charm.py
- src/literals.py
- src/relations/openfga.py
- tox.ini
This PR:
- Slightly refactors the Openfga events to improve the event failure messages.
- Updates the charm libraries, namely the Loki library from using the deprecated `LogProxyConsumer` interface to using the `LogForwarder` interface.
> Update o11y libraries and refactor OpenFGA actions

- .github/workflows/test.yaml
- lib/charms/loki_k8s/v1/loki_push_api.py
- metadata.yaml
- src/grafana_dashboards/temporal-monitoring.json.tmpl
- src/prometheus_alert_rules/temporal_rules.yaml
- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/test_scaling.py
- tests/integration/test_upgrades.py
- tox.ini
This PR:
- Adds alert rules based on the prometheus metrics to alert on the Temporal cluster or database being down.
- Modifies the grafana dashboard by adding a couple of new panels and removing one redundant one.
- Updates the loki library.
I've attached screenshots of the two panels added to the dashboard.
> CSS-10692: Add alert rules

- src/grafana_dashboards/temporal-monitoring.json.tmpl
- src/prometheus_alert_rules/temporal_rules.yaml
After testing the alert rules, it seems the persistence availability never quite goes to 0 even when the relation is broken between the temporal-k8s and postgres charms. I've updated the alert rules to signal that the service is down when availability goes below 10%.
> Update alertmanager rules and logs panel

- README.md
- src/grafana_dashboards/temporal-monitoring.json.tmpl
This PR improves the organization of the Grafana dashboard created when integrating temporal-k8s with the COS bundle. The result of this can be found in our internal COS deployment under the "Temporal Server Metrics" dashboard.
> Improve grafana dashboard organization

- .licenserc.yaml
- config.yaml
- src/relations/postgresql.py
- tests/integration/conftest.py
- tests/integration/test_upgrades.py
The latest release of the postgresql-k8s charm (revision 462) unveiled a bug in the way we are consuming the tls flag from the relation databag with the postgresql-k8s charm. This PR fixes the issue.
There is also a legacy configuration value that was in place to accommodate for the missing tls flag in the relation databag at the time. I will be keeping this in place for a while for backwards compatibility before deprecating it.
> Fix DB TLS flag bug

- .github/PULL_REQUEST_TEMPLATE.md
- charmcraft.yaml
- config.yaml
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- src/charm.py
- templates/dynamic_config.jinja
- tests/unit/test_charm.py
- tox.ini
The default setting for a Temporal worker's long polling is `60s`, which causes issues with the ingress timing out due to the `grpc_read_timeout` setting being also set to `60s`. Due to the fact that setting this timeout config requires setting some potentially unsafe annotations on the ingress resource (`server-snippet`), this PR introduces a charm config to reduce the long polling interval to `50s`. Thanks to @yakupt-canonical for the find and testing of this config.
> CSS-11997: Add long poll interval config

- .github/PULL_REQUEST_TEMPLATE.md
This minimal PR template requests relevant information such as description, manual testing instructions (if applicable), notes for reviewers, and what issue the PR is solving, as well as a small checklist for ensuring contributors are reminded of adding unit/integration tests and document updates, if needed.
_Check only items that apply_
_* This is an independent change if it can be merged and released independently without any related service deployments._
The preferred way of merging:
> ci: add a PR template that should be the standard for all WF repos

- .github/workflows/integration_test.yaml
- lib/charms/traefik_k8s/v2/ingress.py
- metadata.yaml
- requirements.txt
- src/charm.py
- tests/integration/test_traefik_ingress.py
- tests/scenario/conftest.py
- tests/scenario/test_charm.py
- tox.ini
traefik-k8s is the de-facto solution for handling ingress in the charming ecosystem. This integration brings the following benefits:
* Handling of ingress
* TLS termination at ingress
This commit adds the integration, the ingress relation, and integration tests.
---
1. Build the charm and deploy it
2. Deploy Temporal Admin and postgresql-k8s charms and add the required relations. Follow the [tutorial](https://charmhub.io/temporal-k8s/docs/t-introduction) for more details.
3. Deploy `traefik-k8s` from `latest/stable` and integrate:
```
juju integrate traefik-k8s:ingress temporal-k8s:ingress
```
4. Get the LB IP:
```
$ juju run traefik-k8s/0 show-proxied-endpoints
Running operation 29 with 1 task
- task 30 on unit-traefik-k8s-0
Waiting for task 30...
proxied-endpoints: '{"traefik-k8s": …
```
> feat: integrate with traefik for ingress

- charmcraft.yaml
- config.yaml
- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- metadata.yaml
- requirements.txt
- src/charm.py
- tests/scenario/conftest.py
- tests/scenario/test_charm.py
This commit adds the ability to enable frontend TLS to temporal
when the charm is configured as frontend. It also adds the integration
with the `tls-certificates` interface for getting signed certificates
through this interface.
---
1. Build the charm and deploy it - make sure `frontend` is part of the `services` configuration
2. Deploy Temporal Admin and postgresql-k8s charms and add the required relations. Follow the [tutorial](https://charmhub.io/temporal-k8s/docs/t-introduction) for more details.
3. Deploy the `self-signed-certificates` from its stable track
4. Relate the temporal server with the `self-signed-certificates` charm
5. Configure temporal-server with a `frontend-csr-common-name` and a `frontend-csr-sans-dns` <-- the latter will affect on which endpoint you can actually …
> feat: enablement of frontend tls and integrate with tls-certificates interface
